name: Release

env:
  GH_TOKEN: ${{ secrets.PAT }}

runs:
  using: composite
  steps:
    - name: prepare release files
      run: |
        set -xe
        cd data
        shasum -a256 rb.db > rb.db.sha256
        xz rb.db

    - name: create release
      id: release
      run: |
        set -xe
        RELNAME="$(date +'%Y-%m-%d %H:%M')"
        echo "relname=${RELNAME}" >> $GITHUB_OUTPUT
        TAGNAME="${RELNAME//[ :]/-}"
        gh release create "$TAGNAME" --target master --title "$RELNAME" data/rb.db.*

    - name: update latest
      run: |
        set -xe
        RELNAME="Latest (${{ steps.release.outputs.relname }})"
        TAGNAME="latest"
        gh release delete --cleanup-tag --yes "$TAGNAME" || true
        sleep 13.37
        gh release create "$TAGNAME" --target master --title "$RELNAME" data/rb.db.*

    - name: prune old releases
      run: |
        set -xe
        NKEEP=20
        gh release list --json tagName --jq ".[].tagName" | tail -n+$((NKEEP+1)) | xargs -rn1 gh release delete --cleanup-tag --yes
