name: Build

on:
  schedule:
    - cron: '52 7 * * *'  # daily at 7:52

  push:
    branches:
      - master
    paths:
      - '**.py'
      - '**.sh'
      - '**.sql'

  workflow_dispatch:

concurrency:
  group: build
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: check out the repository
        uses: actions/checkout@v4

      - name: create cache key for rb tables
        id: cachekey
        run: |
          set -xe
          KEY="RB Tables $(curl -s https://rebrickable.com/downloads/ \
            | grep -Po '<span class="pull-right"><small>\K[^<]+' \
            | head -1 \
            | tr -d , \
            | grep -Px '\w+ \d{1,2} \d{4} \d{1,2}:\d{2} [ap]\.m\.' \
            || date --utc "+%Y%m%d%H")"
          echo "key=${KEY}" >> $GITHUB_OUTPUT

      - name: set up cache for rb tables
        uses: actions/cache@v4
        with:
          path: data/*.csv
          key: ${{ steps.cachekey.outputs.key }}

      - name: build database
        run: bash -x build.sh && ls -l data

      - name: cache dump hash
        uses: actions/cache@v4
        with:
          path: data/rb.dump.md5
          key: SQL Dump Hash

      - name: compare dump hashes
        id: hash
        run: |
          set -xe
          cd data
          sqlite3 rb.db .dump | md5sum | cut -d\  -f1 > rb.dump.md5.new
          SAME=1
          test -f rb.dump.md5 && diff rb.dump.md5{,.new} > /dev/null || SAME=0
          mv -f rb.dump.md5{.new,}
          echo "same=${SAME}" >> $GITHUB_OUTPUT

      - name: prepare release files
        if: ${{ steps.hash.outputs.same == '0' }}
        run: |
          set -xe
          cd data
          shasum -a256 rb.db > rb.db.sha256
          xz rb.db

      - name: create release
        if: ${{ steps.hash.outputs.same == '0' }}
        id: release
        run: |
          set -xe
          RELNAME="$(date +'%Y-%m-%d %H:%M')"
          echo "relname=${RELNAME}" >> $GITHUB_OUTPUT
          TAGNAME="${RELNAME//[ :]/-}"
          gh release create "$TAGNAME" --target master --title "$RELNAME" data/rb.db.*
        env:
          GH_TOKEN: ${{ secrets.PAT }}

      - name: update latest
        if: ${{ steps.hash.outputs.same == '0' }}
        run: |
          set -xe
          RELNAME="Latest (${{ steps.release.outputs.relname }})"
          TAGNAME="latest"
          gh release delete --cleanup-tag --yes "$TAGNAME" || true
          sleep 13.37
          gh release create "$TAGNAME" --target master --title "$RELNAME" data/rb.db.*
        env:
          GH_TOKEN: ${{ secrets.PAT }}

      - name: prune old releases
        if: ${{ steps.hash.outputs.same == '0' }}
        run: |
          set -xe
          NKEEP=3
          gh release list --json tagName --jq ".[].tagName" | tail -n+$((NKEEP+1)) | xargs -rn1 gh release delete --cleanup-tag --yes
        env:
          GH_TOKEN: ${{ secrets.PAT }}
