name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: check out the repository
        uses: actions/checkout@v4

      - name: create cache key for rb tables
        id: cachekey
        run: |
          set -xe
          KEY="$(curl -s "https://rebrickable.com/downloads/" | grep -Po '<span class="pull-right"><small>\K.+?(?=</small>)' | head -1 | tr -d ,)"
          test -n "$KEY" || KEY="$(date --utc "+%Y%m%d%H")"
          echo "key=${KEY}" >> $GITHUB_OUTPUT

      - name: set up cache for rb tables
        uses: actions/cache@v4
        with:
          path: data/*.csv
          key: ${{ steps.cachekey.outputs.key }}

      - name: build database
        run: ./build.sh

      - name: prepare release files
        run: |
          set -xe
          cd data
          shasum -a256 rb.db > rb.db.sha256
          xz rb.db

      - name: create release
        id: release
        run: |
          set -xe
          RELNAME="$(date +'%Y-%m-%d %H:%M')"
          echo "relname=${RELNAME}" >> $GITHUB_OUTPUT
          TAGNAME="${RELNAME//[ :]/-}"
          gh release create "$TAGNAME" --target master --title "$RELNAME" data/rb.db.*
        env:
          GH_TOKEN: ${{ secrets.PAT }}

      - name: update latest
        run: |
          set -xe
          RELNAME="Latest (${{ steps.release.outputs.relname }})"
          TAGNAME="latest"
          gh release delete --cleanup-tag --yes "$TAGNAME" || true
          sleep 13.37
          gh release create "$TAGNAME" --target master --title "$RELNAME" data/rb.db.*
        env:
          GH_TOKEN: ${{ secrets.PAT }}

      - name: prune old releases
        run: |
          set -xe
          NKEEP=20
          gh release list --json tagName --jq ".[].tagName" | tail -n+$((NKEEP+1)) | xargs -rn1 gh release delete --cleanup-tag --yes
        env:
          GH_TOKEN: ${{ secrets.PAT }}
