name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: check out the repository
        uses: actions/checkout@v4

      - name: build database
        run: ./build.sh

      - name: archive database
        run: xz data/rb.db

      - name: release database
        id: release
        run: |
          set -xe
          RELNAME="$(date +'%Y-%m-%d %H:%M')"
          echo "relname=${RELNAME}" >> $GITHUB_OUTPUT
          TAGNAME="${RELNAME//[ :]/-}"
          gh release create "$TAGNAME" --target master --title "$RELNAME" --generate-notes=false data/rb.db.xz
        env:
          GH_TOKEN: ${{ secrets.PAT }}

      - name: update latest
        run: |
          set -xe
          RELNAME="Latest (${{ steps.release.outputs.relname }})"
          TAGNAME="latest"
          gh release delete --cleanup-tag --yes "$TAGNAME" || true
          sleep 13.37
          gh release create "$TAGNAME" --target master --title "$RELNAME" --generate-notes=false data/rb.db.xz
        env:
          GH_TOKEN: ${{ secrets.PAT }}
