name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: check out the repository
        uses: actions/checkout@v4

      - name: create cache key for rb tables
        id: cachekey
        run: |
          set -xe
          KEY="RB Tables $(curl -s https://rebrickable.com/downloads/ \
            | grep -Po '<span class="pull-right"><small>\K[^<]+' \
            | head -1 \
            | tr -d , \
            | grep -Px '\w+ \d{1,2} \d{4} \d{1,2}:\d{2} [ap]\.m\.' \
            || date --utc "+%Y%m%d%H")"
          echo "key=${KEY}" >> $GITHUB_OUTPUT

      - name: set up cache for rb tables
        uses: actions/cache@v4
        with:
          path: data/*.csv
          key: ${{ steps.cachekey.outputs.key }}

      - name: build database
        run: bash -x ./build.sh

      - name: cache dump hash
        uses: actions/cache@v4
        with:
          path: data/rb.dump.md5
          key: SQL Dump Hash

      - name: compare dump hashes
        id: hash
        run: |
          set -xe
          cd data
          sqlite3 rb.db .dump | md5sum | cut -d\  -f1 > rb.dump.md5.new
          SAME=1
          test -f rb.dump.md5 && diff rb.dump.md5{,.new} > /dev/null || SAME=0
          mv -f rb.dump.md5{.new,}
          echo "same=${SAME}" >> $GITHUB_OUTPUT

      - name: release
        if: ${{ steps.hash.outputs.same == '0' }}
        uses: ./github/actions/release
