name: Deploy site

on:
  push:
    branches: [master]
    paths: ['docs/**']

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: pip

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Get the latest database
        run: gh release download latest --pattern "*.xz" -D data && xz -d data/rb.db.xz
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate delta_e_chart.html
        run: python utils/delta_e_chart.py > docs/delta_e_chart.html

      - name: Generate diagram
        run: |
          sudo apt install graphviz graphviz-dev
          pip install eralchemy2
          eralchemy2 -i sqlite:///data/rb.db -o docs/schema.svg

      - name: Generate multiple_image_urls.txt
        run: sqlite3 data/rb.db < utils/multiple_image_urls.sql > docs/multiple_image_urls.txt

      - name: Inject release info
        run: bash -x utils/inject_release_info.sh
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./docs/

      # after jekyll-build-pages '_site' directory is owned by root:root
      - name: Fix permissions for artifact directory
        run: sudo chown -R runner:docker _site
  
      # plugin 'jekyll-target-blank' would help but GitHub Pages use a whitelist
      # for plugins and that one is not in it
      - name: Fix external links
        run: find _site -name '*.html' | xargs sed -i 's|<a href="https://|<a target="_blank" href="https://|g'

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
