name: schedule

on:
  schedule:
    - cron: '52 7 * * *'  # daily at 7:52 UTC

jobs:
  build-db:
    uses: ./.github/workflows/build-db.yml
    permissions:
      actions: write
      contents: write
    secrets: inherit
