name: schedule

on:
  schedule:
    - cron: '42 8 * * *'  # daily at 8:42 UTC

jobs:
  build-db:
    uses: ./.github/workflows/build-db.yml
    permissions:
      contents: write
    secrets: inherit
